# Deployment of steward
---
- hosts: aws-deploy
  become: false
  vars_files:
    - vars/default.yaml
    - vars/steward.yaml
    - vars/secrets.yaml

  tasks:
    - name: Install steward packages
      become: true
      pacman: name={{ packages }} state=latest

    - name: Checkout steward
      ansible.builtin.git:
        repo: "{{ git_uri }}"
        version: 'dev'
        dest: '~/steward-fastapi'
        accept_hostkey: true
      tags:
        - steward_setup

    - name: Copy custom aerich to server
      ansible.builtin.copy:
        dest: "{{ steward_directory }}"
        src: "{{ python_distributables_directory }}"
        group: "{{ sudo_user }}"
        owner: "{{ sudo_user }}"
        mode:  'preserve'
      tags:
        - steward_setup

    - name: Copy steward prod only directory contents
      ansible.posix.synchronize:
        checksum: true
        dest: "{{ steward_directory }}"
        src: "{{ files_directory }}/steward/"
      tags:
        - steward_setup

    - name: Create project instance dir
      ansible.builtin.file:
        path: "{{ steward_directory }}/instance"
        state: directory
        mode: '0755'
      tags:
        - steward_setup

    - name: Install poetry environment
      ansible.builtin.command:
        chdir: "{{ steward_directory }}"
        cmd: 'poetry install --no-dev'
      tags:
        - steward_setup

    - name: Recreate Database
      delegate_to: 'localhost'
      ansible.builtin.command:
        chdir: "{{ scripts_directory }}"
        cmd: 'bash refresh_database.bash'
      tags:
        - refresh_database
        - never
      register: recreate_database

    - name: Update Database
      ansible.builtin.command:
        chdir: "{{ steward_working_directory }}"
        cmd: 'poetry run aerich upgrade'
      tags:
        - refresh_database
        - never

    - name: Create admin agent
      ansible.builtin.command:
        chdir: "{{ steward_setup_directory }}"
        cmd: 'poetry run python create_admin_agent.py'
      tags:
        - refresh_database
        - never

    - name: Copy root configs
      become: true
      ansible.posix.synchronize:
        checksum: true
        dest: '/etc'
        src: "{{ files_directory }}/etc/"
      register: root_configs
      tags:
        - configs

    - name: Add caddy to group sudo_user
      become: true
      user:
        name: caddy
        state: present
        groups: "{{ sudo_user }}"
        append: true
      tags:
        - caddy

    # TODO:Create a systemd service to create a dir in run on boot for the application
    - name: Reload systemd daemon
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
      when: root_configs.changed
      tags:
        - configs

    - name: Enable webservers
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - 'caddy'
        - 'aulon-web'
        - 'steward-discord'
      tags:
        - configs

